//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreUIDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Users
    {
        public long ID { get; set; }
        public string USERNAME { get; set; }
        public string UserRole { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public bool IS_ACTIVE { get; set; }
    }
}
